This is makeindex, version 2.15 [MiKTeX 2.9.7250 64-bit] (kpathsea + Thai support).
Scanning style file ./00_main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 00_main.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (36 comparisons).
Generating output file 00_main.acr....done (26 lines written, 0 warnings).
Output written in 00_main.acr.
Transcript written in 00_main.alg.
